"""fix: rename column user_name

Revision ID: 61b7b770ffc9
Revises: 7efe45a11fd3
Create Date: 2025-10-03 20:30:28.136833

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '61b7b770ffc9'
down_revision: Union[str, None] = '7efe45a11fd3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('name', sa.String(length=50), nullable=False))
    op.drop_column('users', 'user_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('user_name', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.drop_column('users', 'name')
    # ### end Alembic commands ###