"""добавил диски

Revision ID: ec6a337a9d2a
Revises: 61b7b770ffc9
Create Date: 2025-10-08 10:55:01.607419

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ec6a337a9d2a'
down_revision: Union[str, None] = '61b7b770ffc9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('discs_status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rental_statuses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('general_discs',
    sa.Column('disc_id', sa.BigInteger(), nullable=False),
    sa.Column('game_id', sa.BigInteger(), nullable=False),
    sa.Column('status_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.ForeignKeyConstraint(['status_id'], ['discs_status.id'], ),
    sa.PrimaryKeyConstraint('disc_id')
    )
    op.create_table('rentals',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('disc_id', sa.BigInteger(), nullable=False),
    sa.Column('status_id', sa.BigInteger(), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.Column('expected_end_date', sa.DateTime(), nullable=False),
    sa.Column('actual_end_date', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['disc_id'], ['general_discs.disc_id'], ),
    sa.ForeignKeyConstraint(['status_id'], ['rental_statuses.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rentals')
    op.drop_table('general_discs')
    op.drop_table('rental_statuses')
    op.drop_table('discs_status')
    # ### end Alembic commands ###